node_id: node3
listen_addr: :8005
http_addr: :8006
data_dir: ./data
election_tick: 50
heartbeat_tick: 1
cluster:
  - id: node1
    address: localhost:8001
    http_address: localhost:8002
  - id: node2
    address: localhost:8003
    http_address: localhost:8004
  - id: node3
    address: localhost:8005
    http_address: localhost:8006
