{{- if and .Values.config.adminToken (not .Values.config.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-raft-token
  labels:
    app: {{ .Release.Name }}-raft
type: Opaque
stringData:
  admin-token: {{ .Values.config.adminToken | quote }}
{{- end }}
