// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/etcdcompat/etcd.proto

package etcdcompat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FilterType is used in WatchCreateRequest to filter out event types.
type FilterType int32

const (
	FilterType_NOPUT    FilterType = 0
	FilterType_NODELETE FilterType = 1
)

// Enum value maps for FilterType.
var (
	FilterType_name = map[int32]string{
		0: "NOPUT",
		1: "NODELETE",
	}
	FilterType_value = map[string]int32{
		"NOPUT":    0,
		"NODELETE": 1,
	}
)

func (x FilterType) Enum() *FilterType {
	p := new(FilterType)
	*p = x
	return p
}

func (x FilterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_etcdcompat_etcd_proto_enumTypes[0].Descriptor()
}

func (FilterType) Type() protoreflect.EnumType {
	return &file_proto_etcdcompat_etcd_proto_enumTypes[0]
}

func (x FilterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterType.Descriptor instead.
func (FilterType) EnumDescriptor() ([]byte, []int) {
	return file_proto_etcdcompat_etcd_proto_rawDescGZIP(), []int{0}
}

type Event_EventType int32

const (
	Event_PUT    Event_EventType = 0
	Event_DELETE Event_EventType = 1
)

// Enum value maps for Event_EventType.
var (
	Event_EventType_name = map[int32]string{
		0: "PUT",
		1: "DELETE",
	}
	Event_EventType_value = map[string]int32{
		"PUT":    0,
		"DELETE": 1,
	}
)

func (x Event_EventType) Enum() *Event_EventType {
	p := new(Event_EventType)
	*p = x
	return p
}

func (x Event_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_etcdcompat_etcd_proto_enumTypes[1].Descriptor()
}

func (Event_EventType) Type() protoreflect.EnumType {
	return &file_proto_etcdcompat_etcd_proto_enumTypes[1]
}

func (x Event_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event_EventType.Descriptor instead.
func (Event_EventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_etcdcompat_etcd_proto_rawDescGZIP(), []int{2, 0}
}

// sort_order is the order for returned sorted results.
type RangeRequest_SortOrder int32

const (
	RangeRequest_NONE    RangeRequest_SortOrder = 0
	RangeRequest_ASCEND  RangeRequest_SortOrder = 1
	RangeRequest_DESCEND RangeRequest_SortOrder = 2
)

// Enum value maps for RangeRequest_SortOrder.
var (
	RangeRequest_SortOrder_name = map[int32]string{
		0: "NONE",
		1: "ASCEND",
		2: "DESCEND",
	}
	RangeRequest_SortOrder_value = map[string]int32{
		"NONE":    0,
		"ASCEND":  1,
		"DESCEND": 2,
	}
)

func (x RangeRequest_SortOrder) Enum() *RangeRequest_SortOrder {
	p := new(RangeRequest_SortOrder)
	*p = x
	return p
}

func (x RangeRequest_SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RangeRequest_SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_etcdcompat_etcd_proto_enumTypes[2].Descriptor()
}

func (RangeRequest_SortOrder) Type() protoreflect.EnumType {
	return &file_proto_etcdcompat_etcd_proto_enumTypes[2]
}

func (x RangeRequest_SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RangeRequest_SortOrder.Descriptor instead.
func (RangeRequest_SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_proto_etcdcompat_etcd_proto_rawDescGZIP(), []int{3, 0}
}

// sort_target is the key-value field to use for sorting.
type RangeRequest_SortTarget int32

const (
	RangeRequest_KEY     RangeRequest_SortTarget = 0
	RangeRequest_VERSION RangeRequest_SortTarget = 1
	RangeRequest_CREATE  RangeRequest_SortTarget = 2
	RangeRequest_MOD     RangeRequest_SortTarget = 3
	RangeRequest_VALUE   RangeRequest_SortTarget = 4
)

// Enum value maps for RangeRequest_SortTarget.
var (
	RangeRequest_SortTarget_name = map[int32]string{
		0: "KEY",
		1: "VERSION",
		2: "CREATE",
		3: "MOD",
		4: "VALUE",
	}
	RangeRequest_SortTarget_value = map[string]int32{
		"KEY":     0,
		"VERSION": 1,
		"CREATE":  2,
		"MOD":     3,
		"VALUE":   4,
	}
)

func (x RangeRequest_SortTarget) Enum() *RangeRequest_SortTarget {
	p := new(RangeRequest_SortTarget)
	*p = x
	return p
}

func (x RangeRequest_SortTarget) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RangeRequest_SortTarget) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_etcdcompat_etcd_proto_enumTypes[3].Descriptor()
}

func (RangeRequest_SortTarget) Type() protoreflect.EnumType {
	return &file_proto_etcdcompat_etcd_proto_enumTypes[3]
}

func (x RangeRequest_SortTarget) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RangeRequest_SortTarget.Descriptor instead.
func (RangeRequest_SortTarget) EnumDescriptor() ([]byte, []int) {
	return file_proto_etcdcompat_etcd_proto_rawDescGZIP(), []int{3, 1}
}

type Compare_CompareResult int32

const (
	Compare_EQUAL     Compare_CompareResult = 0
	Compare_GREATER   Compare_CompareResult = 1
	Compare_LESS      Compare_CompareResult = 2
	Compare_NOT_EQUAL Compare_CompareResult = 3
)

// Enum value maps for Compare_CompareResult.
var (
	Compare_CompareResult_name = map[int32]string{
		0: "EQUAL",
		1: "GREATER",
		2: "LESS",
		3: "NOT_EQUAL",
	}
	Compare_CompareResult_value = map[string]int32{
		"EQUAL":     0,
		"GREATER":   1,
		"LESS":      2,
		"NOT_EQUAL": 3,
	}
)

func (x Compare_CompareResult) Enum() *Compare_CompareResult {
	p := new(Compare_CompareResult)
	*p = x
	return p
}

func (x Compare_CompareResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Compare_CompareResult) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_etcdcompat_etcd_proto_enumTypes[4].Descriptor()
}

func (Compare_CompareResult) Type() protoreflect.EnumType {
	return &file_proto_etcdcompat_etcd_proto_enumTypes[4]
}

func (x Compare_CompareResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Compare_CompareResult.Descriptor instead.
func (Compare_CompareResult) EnumDescriptor() ([]byte, []int) {
	return file_proto_etcdcompat_etcd_proto_rawDescGZIP(), []int{9, 0}
}

type Compare_CompareTarget int32

const (
	Compare_VERSION Compare_CompareTarget = 0
	Compare_CREATE  Compare_CompareTarget = 1
	Compare_MOD     Compare_CompareTarget = 2
	Compare_VALUE   Compare_CompareTarget = 3
)

// Enum value maps for Compare_CompareTarget.
var (
	Compare_CompareTarget_name = map[int32]string{
		0: "VERSION",
		1: "CREATE",
		2: "MOD",
		3: "VALUE",
	}
	Compare_CompareTarget_value = map[string]int32{
		"VERSION": 0,
		"CREATE":  1,
		"MOD":     2,
		"VALUE":   3,
	}
)

func (x Compare_CompareTarget) Enum() *Compare_CompareTarget {
	p := new(Compare_CompareTarget)
	*p = x
	return p
}

func (x Compare_CompareTarget) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Compare_CompareTarget) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_etcdcompat_etcd_proto_enumTypes[5].Descriptor()
}

func (Compare_CompareTarget) Type() protoreflect.EnumType {
	return &file_proto_etcdcompat_etcd_proto_enumTypes[5]
}

func (x Compare_CompareTarget) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Compare_CompareTarget.Descriptor instead.
func (Compare_CompareTarget) EnumDescriptor() ([]byte, []int) {
	return file_proto_etcdcompat_etcd_proto_rawDescGZIP(), []int{9, 1}
}

// ResponseHeader is included in every response to identify which cluster
// member answered and at what revision.
type ResponseHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cluster_id is the unique identifier for the cluster.
	ClusterId uint64 `protobuf:"varint,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// member_id is the ID of the member that generated the response.
	MemberId uint64 `protobuf:"varint,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	// revision is the key-value store revision at the time of the response.
	Revision int64 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	// raft_term is the raft term at the time of the response.
	RaftTerm      uint64 `protobuf:"varint,4,opt,name=raft_term,json=raftTerm,proto3" json:"raft_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseHeader) Reset() {
	*x = ResponseHeader{}
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseHeader) ProtoMessage() {}

func (x *ResponseHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseHeader.ProtoReflect.Descriptor instead.
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return file_proto_etcdcompat_etcd_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseHeader) GetClusterId() uint64 {
	if x != nil {
		return x.ClusterId
	}
	return 0
}

func (x *ResponseHeader) GetMemberId() uint64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *ResponseHeader) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ResponseHeader) GetRaftTerm() uint64 {
	if x != nil {
		return x.RaftTerm
	}
	return 0
}

// KeyValue is the etcd-compatible versioned key-value pair.
type KeyValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key is the key in bytes.
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// create_revision is the revision of the last creation on this key.
	CreateRevision int64 `protobuf:"varint,2,opt,name=create_revision,json=createRevision,proto3" json:"create_revision,omitempty"`
	// mod_revision is the revision of the last modification on this key.
	ModRevision int64 `protobuf:"varint,3,opt,name=mod_revision,json=modRevision,proto3" json:"mod_revision,omitempty"`
	// version is the version of the key. A deletion resets the version to zero
	// and any modification of the key increases its version.
	Version int64 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	// value is the value held by the key, in bytes.
	Value []byte `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	// lease is the ID of the lease that attached to key. When the attached
	// lease expires, the key will be deleted. If lease is 0, then no lease
	// is attached to the key.
	Lease         int64 `protobuf:"varint,6,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_proto_etcdcompat_etcd_proto_rawDescGZIP(), []int{1}
}

func (x *KeyValue) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyValue) GetCreateRevision() int64 {
	if x != nil {
		return x.CreateRevision
	}
	return 0
}

func (x *KeyValue) GetModRevision() int64 {
	if x != nil {
		return x.ModRevision
	}
	return 0
}

func (x *KeyValue) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *KeyValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KeyValue) GetLease() int64 {
	if x != nil {
		return x.Lease
	}
	return 0
}

// Event models a key-value change notification delivered via Watch.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type is the kind of event. If type is a PUT, it indicates new data has
	// been stored to the key. If type is a DELETE, it indicates the key was
	// deleted.
	Type Event_EventType `protobuf:"varint,1,opt,name=type,proto3,enum=etcdcompat.Event_EventType" json:"type,omitempty"`
	// kv holds the KeyValue for the event.
	// A PUT event contains current kv pair.
	// A DELETE event contains the deleted key with its mod revision set to
	// the revision of the deletion.
	Kv *KeyValue `protobuf:"bytes,2,opt,name=kv,proto3" json:"kv,omitempty"`
	// prev_kv holds the previous KeyValue before the event takes effect.
	// If the event type is PUT, then prev_kv is the previous key-value
	// before the put (only populated when the watch request requested
	// prev_kv). If the event type is DELETE, then prev_kv is the last
	// value of the key before deletion.
	PrevKv        *KeyValue `protobuf:"bytes,3,opt,name=prev_kv,json=prevKv,proto3" json:"prev_kv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_etcdcompat_etcd_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetType() Event_EventType {
	if x != nil {
		return x.Type
	}
	return Event_PUT
}

func (x *Event) GetKv() *KeyValue {
	if x != nil {
		return x.Kv
	}
	return nil
}

func (x *Event) GetPrevKv() *KeyValue {
	if x != nil {
		return x.PrevKv
	}
	return nil
}

type RangeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key is the first key for the range. If range_end is not given, the
	// request only looks up key.
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// range_end is the upper bound on the requested range [key, range_end).
	// If range_end is '\0', the range is all keys >= key.
	// If range_end is key plus one (e.g., "aa"+1 == "ab", "a\xff"+1 == "b"),
	// then the range request gets all keys prefixed with key.
	// If both key and range_end are '\0', then the range request returns all
	// keys.
	RangeEnd []byte `protobuf:"bytes,2,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`
	// limit is a cap on the number of returned keys. 0 means no limit.
	Limit int64 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// revision is the point-in-time of the key-value store to use for the
	// range. If revision is less or equal to zero, the range is over the
	// newest key-value store. If the revision has been compacted, ErrCompacted
	// is returned as a response.
	Revision   int64                   `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	SortOrder  RangeRequest_SortOrder  `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3,enum=etcdcompat.RangeRequest_SortOrder" json:"sort_order,omitempty"`
	SortTarget RangeRequest_SortTarget `protobuf:"varint,6,opt,name=sort_target,json=sortTarget,proto3,enum=etcdcompat.RangeRequest_SortTarget" json:"sort_target,omitempty"`
	// serializable sets the range request to use serializable member-local
	// reads. Range requests are linearizable by default; linearizable requests
	// have higher latency and lower throughput than serializable requests but
	// reflect the current consensus of the cluster. For better performance, in
	// exchange for possible stale reads, a serializable range request is
	// served locally without needing to reach consensus with other nodes in
	// the cluster.
	Serializable bool `protobuf:"varint,7,opt,name=serializable,proto3" json:"serializable,omitempty"`
	// keys_only when set returns only the keys and not the values.
	KeysOnly bool `protobuf:"varint,8,opt,name=keys_only,json=keysOnly,proto3" json:"keys_only,omitempty"`
	// count_only when set returns only the count of the keys in the range.
	CountOnly bool `protobuf:"varint,9,opt,name=count_only,json=countOnly,proto3" json:"count_only,omitempty"`
	// min_mod_revision is the lower bound for returned key mod revisions; all
	// keys with lesser mod revisions will be filtered away.
	MinModRevision int64 `protobuf:"varint,10,opt,name=min_mod_revision,json=minModRevision,proto3" json:"min_mod_revision,omitempty"`
	// max_mod_revision is the upper bound for returned key mod revisions; all
	// keys with greater mod revisions will be filtered away.
	MaxModRevision int64 `protobuf:"varint,11,opt,name=max_mod_revision,json=maxModRevision,proto3" json:"max_mod_revision,omitempty"`
	// min_create_revision is the lower bound for returned key create revisions;
	// all keys with lesser create revisions will be filtered away.
	MinCreateRevision int64 `protobuf:"varint,12,opt,name=min_create_revision,json=minCreateRevision,proto3" json:"min_create_revision,omitempty"`
	// max_create_revision is the upper bound for returned key create revisions;
	// all keys with greater create revisions will be filtered away.
	MaxCreateRevision int64 `protobuf:"varint,13,opt,name=max_create_revision,json=maxCreateRevision,proto3" json:"max_create_revision,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RangeRequest) Reset() {
	*x = RangeRequest{}
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeRequest) ProtoMessage() {}

func (x *RangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeRequest.ProtoReflect.Descriptor instead.
func (*RangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_etcdcompat_etcd_proto_rawDescGZIP(), []int{3}
}

func (x *RangeRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RangeRequest) GetRangeEnd() []byte {
	if x != nil {
		return x.RangeEnd
	}
	return nil
}

func (x *RangeRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RangeRequest) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *RangeRequest) GetSortOrder() RangeRequest_SortOrder {
	if x != nil {
		return x.SortOrder
	}
	return RangeRequest_NONE
}

func (x *RangeRequest) GetSortTarget() RangeRequest_SortTarget {
	if x != nil {
		return x.SortTarget
	}
	return RangeRequest_KEY
}

func (x *RangeRequest) GetSerializable() bool {
	if x != nil {
		return x.Serializable
	}
	return false
}

func (x *RangeRequest) GetKeysOnly() bool {
	if x != nil {
		return x.KeysOnly
	}
	return false
}

func (x *RangeRequest) GetCountOnly() bool {
	if x != nil {
		return x.CountOnly
	}
	return false
}

func (x *RangeRequest) GetMinModRevision() int64 {
	if x != nil {
		return x.MinModRevision
	}
	return 0
}

func (x *RangeRequest) GetMaxModRevision() int64 {
	if x != nil {
		return x.MaxModRevision
	}
	return 0
}

func (x *RangeRequest) GetMinCreateRevision() int64 {
	if x != nil {
		return x.MinCreateRevision
	}
	return 0
}

func (x *RangeRequest) GetMaxCreateRevision() int64 {
	if x != nil {
		return x.MaxCreateRevision
	}
	return 0
}

type RangeResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// kvs is the list of key-value pairs matched by the range request.
	// kvs is empty when count is requested.
	Kvs []*KeyValue `protobuf:"bytes,2,rep,name=kvs,proto3" json:"kvs,omitempty"`
	// more indicates if there are more keys to return in the requested range.
	More bool `protobuf:"varint,3,opt,name=more,proto3" json:"more,omitempty"`
	// count is set to the number of keys within the range when requested.
	Count         int64 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeResponse) Reset() {
	*x = RangeResponse{}
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeResponse) ProtoMessage() {}

func (x *RangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeResponse.ProtoReflect.Descriptor instead.
func (*RangeResponse) Descriptor() ([]byte, []int) {
	return file_proto_etcdcompat_etcd_proto_rawDescGZIP(), []int{4}
}

func (x *RangeResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RangeResponse) GetKvs() []*KeyValue {
	if x != nil {
		return x.Kvs
	}
	return nil
}

func (x *RangeResponse) GetMore() bool {
	if x != nil {
		return x.More
	}
	return false
}

func (x *RangeResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type PutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key is the key, in bytes, to put into the key-value store.
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// value is the value, in bytes, to associate with the key in the
	// key-value store.
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// lease is the lease ID to associate with the key in the key-value store.
	// A lease value of 0 indicates no lease.
	Lease int64 `protobuf:"varint,3,opt,name=lease,proto3" json:"lease,omitempty"`
	// prev_kv if set, gets the previous key-value pair before changing it.
	// The previous key-value pair will be returned in the put response.
	PrevKv bool `protobuf:"varint,4,opt,name=prev_kv,json=prevKv,proto3" json:"prev_kv,omitempty"`
	// ignore_value updates the key using its current value. Returns an error
	// if the key does not exist.
	IgnoreValue bool `protobuf:"varint,5,opt,name=ignore_value,json=ignoreValue,proto3" json:"ignore_value,omitempty"`
	// ignore_lease updates the key using its current lease. Returns an error
	// if the key does not exist.
	IgnoreLease   bool `protobuf:"varint,6,opt,name=ignore_lease,json=ignoreLease,proto3" json:"ignore_lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_proto_etcdcompat_etcd_proto_rawDescGZIP(), []int{5}
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutRequest) GetLease() int64 {
	if x != nil {
		return x.Lease
	}
	return 0
}

func (x *PutRequest) GetPrevKv() bool {
	if x != nil {
		return x.PrevKv
	}
	return false
}

func (x *PutRequest) GetIgnoreValue() bool {
	if x != nil {
		return x.IgnoreValue
	}
	return false
}

func (x *PutRequest) GetIgnoreLease() bool {
	if x != nil {
		return x.IgnoreLease
	}
	return false
}

type PutResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// if prev_kv is set in the request, the previous key-value pair will be
	// returned.
	PrevKv        *KeyValue `protobuf:"bytes,2,opt,name=prev_kv,json=prevKv,proto3" json:"prev_kv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_proto_etcdcompat_etcd_proto_rawDescGZIP(), []int{6}
}

func (x *PutResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PutResponse) GetPrevKv() *KeyValue {
	if x != nil {
		return x.PrevKv
	}
	return nil
}

type DeleteRangeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key is the first key to delete in the range.
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// range_end is the key following the last key to delete for the range
	// [key, range_end). If range_end is not given, the range is defined to
	// contain only the key argument. If range_end is one bit larger than the
	// given key, then all keys with the prefix (the given key) will be
	// deleted. If range_end is '\0', all keys greater than or equal to the
	// key argument will be deleted.
	RangeEnd []byte `protobuf:"bytes,2,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`
	// prev_kv when set returns the contents of the deleted key-value pairs.
	PrevKv        bool `protobuf:"varint,3,opt,name=prev_kv,json=prevKv,proto3" json:"prev_kv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRangeRequest) Reset() {
	*x = DeleteRangeRequest{}
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRangeRequest) ProtoMessage() {}

func (x *DeleteRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRangeRequest.ProtoReflect.Descriptor instead.
func (*DeleteRangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_etcdcompat_etcd_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRangeRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *DeleteRangeRequest) GetRangeEnd() []byte {
	if x != nil {
		return x.RangeEnd
	}
	return nil
}

func (x *DeleteRangeRequest) GetPrevKv() bool {
	if x != nil {
		return x.PrevKv
	}
	return false
}

type DeleteRangeResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// deleted is the number of keys deleted by the delete range request.
	Deleted int64 `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	// prev_kvs is a list of all key-value pairs deleted by the request
	// (only populated when prev_kv is set in the request).
	PrevKvs       []*KeyValue `protobuf:"bytes,3,rep,name=prev_kvs,json=prevKvs,proto3" json:"prev_kvs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRangeResponse) Reset() {
	*x = DeleteRangeResponse{}
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRangeResponse) ProtoMessage() {}

func (x *DeleteRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRangeResponse.ProtoReflect.Descriptor instead.
func (*DeleteRangeResponse) Descriptor() ([]byte, []int) {
	return file_proto_etcdcompat_etcd_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRangeResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DeleteRangeResponse) GetDeleted() int64 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

func (x *DeleteRangeResponse) GetPrevKvs() []*KeyValue {
	if x != nil {
		return x.PrevKvs
	}
	return nil
}

// Compare is a predicate that represents one comparison from a conditional
// transaction request.
type Compare struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// result is logical comparison operation for this comparison.
	Result Compare_CompareResult `protobuf:"varint,1,opt,name=result,proto3,enum=etcdcompat.Compare_CompareResult" json:"result,omitempty"`
	// target is the key-value field to inspect for the comparison.
	Target Compare_CompareTarget `protobuf:"varint,2,opt,name=target,proto3,enum=etcdcompat.Compare_CompareTarget" json:"target,omitempty"`
	// key is the subject key for the comparison operation.
	Key []byte `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to TargetUnion:
	//
	//	*Compare_Version
	//	*Compare_CreateRevision
	//	*Compare_ModRevision
	//	*Compare_Value
	TargetUnion isCompare_TargetUnion `protobuf_oneof:"target_union"`
	// range_end compares the given target to all keys in the range [key,
	// range_end). See RangeRequest for more details on key ranges.
	RangeEnd      []byte `protobuf:"bytes,64,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Compare) Reset() {
	*x = Compare{}
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Compare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Compare) ProtoMessage() {}

func (x *Compare) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Compare.ProtoReflect.Descriptor instead.
func (*Compare) Descriptor() ([]byte, []int) {
	return file_proto_etcdcompat_etcd_proto_rawDescGZIP(), []int{9}
}

func (x *Compare) GetResult() Compare_CompareResult {
	if x != nil {
		return x.Result
	}
	return Compare_EQUAL
}

func (x *Compare) GetTarget() Compare_CompareTarget {
	if x != nil {
		return x.Target
	}
	return Compare_VERSION
}

func (x *Compare) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Compare) GetTargetUnion() isCompare_TargetUnion {
	if x != nil {
		return x.TargetUnion
	}
	return nil
}

func (x *Compare) GetVersion() int64 {
	if x != nil {
		if x, ok := x.TargetUnion.(*Compare_Version); ok {
			return x.Version
		}
	}
	return 0
}

func (x *Compare) GetCreateRevision() int64 {
	if x != nil {
		if x, ok := x.TargetUnion.(*Compare_CreateRevision); ok {
			return x.CreateRevision
		}
	}
	return 0
}

func (x *Compare) GetModRevision() int64 {
	if x != nil {
		if x, ok := x.TargetUnion.(*Compare_ModRevision); ok {
			return x.ModRevision
		}
	}
	return 0
}

func (x *Compare) GetValue() []byte {
	if x != nil {
		if x, ok := x.TargetUnion.(*Compare_Value); ok {
			return x.Value
		}
	}
	return nil
}

func (x *Compare) GetRangeEnd() []byte {
	if x != nil {
		return x.RangeEnd
	}
	return nil
}

type isCompare_TargetUnion interface {
	isCompare_TargetUnion()
}

type Compare_Version struct {
	// version is the version of the given key.
	Version int64 `protobuf:"varint,4,opt,name=version,proto3,oneof"`
}

type Compare_CreateRevision struct {
	// create_revision is the creation revision of the given key.
	CreateRevision int64 `protobuf:"varint,5,opt,name=create_revision,json=createRevision,proto3,oneof"`
}

type Compare_ModRevision struct {
	// mod_revision is the last modified revision of the given key.
	ModRevision int64 `protobuf:"varint,6,opt,name=mod_revision,json=modRevision,proto3,oneof"`
}

type Compare_Value struct {
	// value is the value of the given key, in bytes.
	Value []byte `protobuf:"bytes,7,opt,name=value,proto3,oneof"`
}

func (*Compare_Version) isCompare_TargetUnion() {}

func (*Compare_CreateRevision) isCompare_TargetUnion() {}

func (*Compare_ModRevision) isCompare_TargetUnion() {}

func (*Compare_Value) isCompare_TargetUnion() {}

// RequestOp holds a request that may be applied in a transaction. Exactly one
// field must be set.
type RequestOp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*RequestOp_RequestRange
	//	*RequestOp_RequestPut
	//	*RequestOp_RequestDeleteRange
	//	*RequestOp_RequestTxn
	Request       isRequestOp_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestOp) Reset() {
	*x = RequestOp{}
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestOp) ProtoMessage() {}

func (x *RequestOp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestOp.ProtoReflect.Descriptor instead.
func (*RequestOp) Descriptor() ([]byte, []int) {
	return file_proto_etcdcompat_etcd_proto_rawDescGZIP(), []int{10}
}

func (x *RequestOp) GetRequest() isRequestOp_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *RequestOp) GetRequestRange() *RangeRequest {
	if x != nil {
		if x, ok := x.Request.(*RequestOp_RequestRange); ok {
			return x.RequestRange
		}
	}
	return nil
}

func (x *RequestOp) GetRequestPut() *PutRequest {
	if x != nil {
		if x, ok := x.Request.(*RequestOp_RequestPut); ok {
			return x.RequestPut
		}
	}
	return nil
}

func (x *RequestOp) GetRequestDeleteRange() *DeleteRangeRequest {
	if x != nil {
		if x, ok := x.Request.(*RequestOp_RequestDeleteRange); ok {
			return x.RequestDeleteRange
		}
	}
	return nil
}

func (x *RequestOp) GetRequestTxn() *TxnRequest {
	if x != nil {
		if x, ok := x.Request.(*RequestOp_RequestTxn); ok {
			return x.RequestTxn
		}
	}
	return nil
}

type isRequestOp_Request interface {
	isRequestOp_Request()
}

type RequestOp_RequestRange struct {
	RequestRange *RangeRequest `protobuf:"bytes,1,opt,name=request_range,json=requestRange,proto3,oneof"`
}

type RequestOp_RequestPut struct {
	RequestPut *PutRequest `protobuf:"bytes,2,opt,name=request_put,json=requestPut,proto3,oneof"`
}

type RequestOp_RequestDeleteRange struct {
	RequestDeleteRange *DeleteRangeRequest `protobuf:"bytes,3,opt,name=request_delete_range,json=requestDeleteRange,proto3,oneof"`
}

type RequestOp_RequestTxn struct {
	RequestTxn *TxnRequest `protobuf:"bytes,4,opt,name=request_txn,json=requestTxn,proto3,oneof"`
}

func (*RequestOp_RequestRange) isRequestOp_Request() {}

func (*RequestOp_RequestPut) isRequestOp_Request() {}

func (*RequestOp_RequestDeleteRange) isRequestOp_Request() {}

func (*RequestOp_RequestTxn) isRequestOp_Request() {}

// ResponseOp holds a response corresponding to the applied request in a
// transaction.
type ResponseOp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*ResponseOp_ResponseRange
	//	*ResponseOp_ResponsePut
	//	*ResponseOp_ResponseDeleteRange
	//	*ResponseOp_ResponseTxn
	Response      isResponseOp_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseOp) Reset() {
	*x = ResponseOp{}
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseOp) ProtoMessage() {}

func (x *ResponseOp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseOp.ProtoReflect.Descriptor instead.
func (*ResponseOp) Descriptor() ([]byte, []int) {
	return file_proto_etcdcompat_etcd_proto_rawDescGZIP(), []int{11}
}

func (x *ResponseOp) GetResponse() isResponseOp_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ResponseOp) GetResponseRange() *RangeResponse {
	if x != nil {
		if x, ok := x.Response.(*ResponseOp_ResponseRange); ok {
			return x.ResponseRange
		}
	}
	return nil
}

func (x *ResponseOp) GetResponsePut() *PutResponse {
	if x != nil {
		if x, ok := x.Response.(*ResponseOp_ResponsePut); ok {
			return x.ResponsePut
		}
	}
	return nil
}

func (x *ResponseOp) GetResponseDeleteRange() *DeleteRangeResponse {
	if x != nil {
		if x, ok := x.Response.(*ResponseOp_ResponseDeleteRange); ok {
			return x.ResponseDeleteRange
		}
	}
	return nil
}

func (x *ResponseOp) GetResponseTxn() *TxnResponse {
	if x != nil {
		if x, ok := x.Response.(*ResponseOp_ResponseTxn); ok {
			return x.ResponseTxn
		}
	}
	return nil
}

type isResponseOp_Response interface {
	isResponseOp_Response()
}

type ResponseOp_ResponseRange struct {
	ResponseRange *RangeResponse `protobuf:"bytes,1,opt,name=response_range,json=responseRange,proto3,oneof"`
}

type ResponseOp_ResponsePut struct {
	ResponsePut *PutResponse `protobuf:"bytes,2,opt,name=response_put,json=responsePut,proto3,oneof"`
}

type ResponseOp_ResponseDeleteRange struct {
	ResponseDeleteRange *DeleteRangeResponse `protobuf:"bytes,3,opt,name=response_delete_range,json=responseDeleteRange,proto3,oneof"`
}

type ResponseOp_ResponseTxn struct {
	ResponseTxn *TxnResponse `protobuf:"bytes,4,opt,name=response_txn,json=responseTxn,proto3,oneof"`
}

func (*ResponseOp_ResponseRange) isResponseOp_Response() {}

func (*ResponseOp_ResponsePut) isResponseOp_Response() {}

func (*ResponseOp_ResponseDeleteRange) isResponseOp_Response() {}

func (*ResponseOp_ResponseTxn) isResponseOp_Response() {}

type TxnRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// compare is a list of predicates representing a conjunction of terms.
	// If the comparisons succeed, then the success requests will be processed
	// in order, and the response will contain their respective responses in
	// order. If the comparisons fail, then the failure requests will be
	// processed in order, and the response will contain their respective
	// responses in order.
	Compare []*Compare `protobuf:"bytes,1,rep,name=compare,proto3" json:"compare,omitempty"`
	// success is a list of requests which will be applied when compare
	// evaluates to true.
	Success []*RequestOp `protobuf:"bytes,2,rep,name=success,proto3" json:"success,omitempty"`
	// failure is a list of requests which will be applied when compare
	// evaluates to false.
	Failure       []*RequestOp `protobuf:"bytes,3,rep,name=failure,proto3" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnRequest) Reset() {
	*x = TxnRequest{}
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnRequest) ProtoMessage() {}

func (x *TxnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnRequest.ProtoReflect.Descriptor instead.
func (*TxnRequest) Descriptor() ([]byte, []int) {
	return file_proto_etcdcompat_etcd_proto_rawDescGZIP(), []int{12}
}

func (x *TxnRequest) GetCompare() []*Compare {
	if x != nil {
		return x.Compare
	}
	return nil
}

func (x *TxnRequest) GetSuccess() []*RequestOp {
	if x != nil {
		return x.Success
	}
	return nil
}

func (x *TxnRequest) GetFailure() []*RequestOp {
	if x != nil {
		return x.Failure
	}
	return nil
}

type TxnResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// succeeded is set to true if the compare evaluated to true or false
	// otherwise.
	Succeeded bool `protobuf:"varint,2,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	// responses is a list of responses corresponding to the results from
	// applying success if succeeded is true or failure if succeeded is false.
	Responses     []*ResponseOp `protobuf:"bytes,3,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnResponse) Reset() {
	*x = TxnResponse{}
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnResponse) ProtoMessage() {}

func (x *TxnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnResponse.ProtoReflect.Descriptor instead.
func (*TxnResponse) Descriptor() ([]byte, []int) {
	return file_proto_etcdcompat_etcd_proto_rawDescGZIP(), []int{13}
}

func (x *TxnResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *TxnResponse) GetSucceeded() bool {
	if x != nil {
		return x.Succeeded
	}
	return false
}

func (x *TxnResponse) GetResponses() []*ResponseOp {
	if x != nil {
		return x.Responses
	}
	return nil
}

type WatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RequestUnion:
	//
	//	*WatchRequest_CreateRequest
	//	*WatchRequest_CancelRequest
	//	*WatchRequest_ProgressRequest
	RequestUnion  isWatchRequest_RequestUnion `protobuf_oneof:"request_union"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_etcdcompat_etcd_proto_rawDescGZIP(), []int{14}
}

func (x *WatchRequest) GetRequestUnion() isWatchRequest_RequestUnion {
	if x != nil {
		return x.RequestUnion
	}
	return nil
}

func (x *WatchRequest) GetCreateRequest() *WatchCreateRequest {
	if x != nil {
		if x, ok := x.RequestUnion.(*WatchRequest_CreateRequest); ok {
			return x.CreateRequest
		}
	}
	return nil
}

func (x *WatchRequest) GetCancelRequest() *WatchCancelRequest {
	if x != nil {
		if x, ok := x.RequestUnion.(*WatchRequest_CancelRequest); ok {
			return x.CancelRequest
		}
	}
	return nil
}

func (x *WatchRequest) GetProgressRequest() *WatchProgressRequest {
	if x != nil {
		if x, ok := x.RequestUnion.(*WatchRequest_ProgressRequest); ok {
			return x.ProgressRequest
		}
	}
	return nil
}

type isWatchRequest_RequestUnion interface {
	isWatchRequest_RequestUnion()
}

type WatchRequest_CreateRequest struct {
	CreateRequest *WatchCreateRequest `protobuf:"bytes,1,opt,name=create_request,json=createRequest,proto3,oneof"`
}

type WatchRequest_CancelRequest struct {
	CancelRequest *WatchCancelRequest `protobuf:"bytes,2,opt,name=cancel_request,json=cancelRequest,proto3,oneof"`
}

type WatchRequest_ProgressRequest struct {
	ProgressRequest *WatchProgressRequest `protobuf:"bytes,3,opt,name=progress_request,json=progressRequest,proto3,oneof"`
}

func (*WatchRequest_CreateRequest) isWatchRequest_RequestUnion() {}

func (*WatchRequest_CancelRequest) isWatchRequest_RequestUnion() {}

func (*WatchRequest_ProgressRequest) isWatchRequest_RequestUnion() {}

type WatchCreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key is the key to register for watching.
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// range_end is the end of the range [key, range_end) to watch. If
	// range_end is not given, only the key argument is watched. If range_end
	// is equal to '\0', all keys greater than or equal to the key argument
	// are watched.
	RangeEnd []byte `protobuf:"bytes,2,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`
	// start_revision is an optional revision to watch from (inclusive). No
	// start_revision is "now".
	StartRevision int64 `protobuf:"varint,3,opt,name=start_revision,json=startRevision,proto3" json:"start_revision,omitempty"`
	// progress_notify is set to make the watchserver send a periodic progress
	// notify event, so that the client knows the processing level of events.
	// When watch_id is provided, the server will periodically send a
	// WatchResponse with no events to the new watcher if there are no recent
	// events. It is useful when clients wish to recover a disconnected watcher
	// starting from a recent known revision.
	ProgressNotify bool `protobuf:"varint,4,opt,name=progress_notify,json=progressNotify,proto3" json:"progress_notify,omitempty"`
	// filter removes the specified kind of events from the watch stream.
	Filters []FilterType `protobuf:"varint,5,rep,packed,name=filters,proto3,enum=etcdcompat.FilterType" json:"filters,omitempty"`
	// If prev_kv is set, created watcher gets the previous KV before the
	// event happens. If the previous KV is already compacted, nothing will be
	// returned.
	PrevKv bool `protobuf:"varint,6,opt,name=prev_kv,json=prevKv,proto3" json:"prev_kv,omitempty"`
	// If watch_id is provided and non-zero, it will be assigned to this
	// watcher (0 means auto-assign). Since creating a watcher in etcd is not
	// an atomic operation, this can be used to ensure that watchers do not
	// miss events if there is a temporary watcher creating/closing race.
	WatchId int64 `protobuf:"varint,7,opt,name=watch_id,json=watchId,proto3" json:"watch_id,omitempty"`
	// fragment enables splitting large revisions into multiple events.
	Fragment      bool `protobuf:"varint,8,opt,name=fragment,proto3" json:"fragment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchCreateRequest) Reset() {
	*x = WatchCreateRequest{}
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchCreateRequest) ProtoMessage() {}

func (x *WatchCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchCreateRequest.ProtoReflect.Descriptor instead.
func (*WatchCreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_etcdcompat_etcd_proto_rawDescGZIP(), []int{15}
}

func (x *WatchCreateRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *WatchCreateRequest) GetRangeEnd() []byte {
	if x != nil {
		return x.RangeEnd
	}
	return nil
}

func (x *WatchCreateRequest) GetStartRevision() int64 {
	if x != nil {
		return x.StartRevision
	}
	return 0
}

func (x *WatchCreateRequest) GetProgressNotify() bool {
	if x != nil {
		return x.ProgressNotify
	}
	return false
}

func (x *WatchCreateRequest) GetFilters() []FilterType {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *WatchCreateRequest) GetPrevKv() bool {
	if x != nil {
		return x.PrevKv
	}
	return false
}

func (x *WatchCreateRequest) GetWatchId() int64 {
	if x != nil {
		return x.WatchId
	}
	return 0
}

func (x *WatchCreateRequest) GetFragment() bool {
	if x != nil {
		return x.Fragment
	}
	return false
}

type WatchCancelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// watch_id is the watcher id to cancel so that no more events are
	// transmitted.
	WatchId       int64 `protobuf:"varint,1,opt,name=watch_id,json=watchId,proto3" json:"watch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchCancelRequest) Reset() {
	*x = WatchCancelRequest{}
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchCancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchCancelRequest) ProtoMessage() {}

func (x *WatchCancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchCancelRequest.ProtoReflect.Descriptor instead.
func (*WatchCancelRequest) Descriptor() ([]byte, []int) {
	return file_proto_etcdcompat_etcd_proto_rawDescGZIP(), []int{16}
}

func (x *WatchCancelRequest) GetWatchId() int64 {
	if x != nil {
		return x.WatchId
	}
	return 0
}

// WatchProgressRequest requests a progress notification.
type WatchProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchProgressRequest) Reset() {
	*x = WatchProgressRequest{}
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchProgressRequest) ProtoMessage() {}

func (x *WatchProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchProgressRequest.ProtoReflect.Descriptor instead.
func (*WatchProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_etcdcompat_etcd_proto_rawDescGZIP(), []int{17}
}

type WatchResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// watch_id is the ID of the watcher that corresponds to the response.
	WatchId int64 `protobuf:"varint,2,opt,name=watch_id,json=watchId,proto3" json:"watch_id,omitempty"`
	// created is set to true if the response is for a create watch request.
	// The client should record the watch_id and expect to receive events for
	// the created watcher from the same stream.
	// All events sent to the created watcher will attach with the same
	// watch_id.
	Created bool `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	// canceled is set to true if the response is for a cancel watch request.
	// No further events will be sent to the canceled watcher.
	Canceled bool `protobuf:"varint,4,opt,name=canceled,proto3" json:"canceled,omitempty"`
	// compact_revision is set to the minimum index if a watcher tries to
	// watch at a compacted index.
	// This happens when creating a watcher at a compacted revision or the
	// watcher cannot catch up with the progress of the key-value store.
	// The client should treat the watcher as canceled and should not try to
	// create any watcher with the same start_revision again.
	CompactRevision int64 `protobuf:"varint,5,opt,name=compact_revision,json=compactRevision,proto3" json:"compact_revision,omitempty"`
	// cancel_reason indicates the reason for canceling the watcher.
	CancelReason string `protobuf:"bytes,6,opt,name=cancel_reason,json=cancelReason,proto3" json:"cancel_reason,omitempty"`
	// fragment is true if large watch response was split over multiple
	// responses.
	Fragment bool `protobuf:"varint,7,opt,name=fragment,proto3" json:"fragment,omitempty"`
	// events is a list of events from the store.
	Events        []*Event `protobuf:"bytes,11,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_etcdcompat_etcd_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_etcdcompat_etcd_proto_rawDescGZIP(), []int{18}
}

func (x *WatchResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *WatchResponse) GetWatchId() int64 {
	if x != nil {
		return x.WatchId
	}
	return 0
}

func (x *WatchResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *WatchResponse) GetCanceled() bool {
	if x != nil {
		return x.Canceled
	}
	return false
}

func (x *WatchResponse) GetCompactRevision() int64 {
	if x != nil {
		return x.CompactRevision
	}
	return 0
}

func (x *WatchResponse) GetCancelReason() string {
	if x != nil {
		return x.CancelReason
	}
	return ""
}

func (x *WatchResponse) GetFragment() bool {
	if x != nil {
		return x.Fragment
	}
	return false
}

func (x *WatchResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_proto_etcdcompat_etcd_proto protoreflect.FileDescriptor

const file_proto_etcdcompat_etcd_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/etcdcompat/etcd.proto\x12\n" +
	"etcdcompat\"\x85\x01\n" +
	"\x0eResponseHeader\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\x04R\tclusterId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\x04R\bmemberId\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x03R\brevision\x12\x1b\n" +
	"\traft_term\x18\x04 \x01(\x04R\braftTerm\"\xae\x01\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12'\n" +
	"\x0fcreate_revision\x18\x02 \x01(\x03R\x0ecreateRevision\x12!\n" +
	"\fmod_revision\x18\x03 \x01(\x03R\vmodRevision\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12\x14\n" +
	"\x05value\x18\x05 \x01(\fR\x05value\x12\x14\n" +
	"\x05lease\x18\x06 \x01(\x03R\x05lease\"\xaf\x01\n" +
	"\x05Event\x12/\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1b.etcdcompat.Event.EventTypeR\x04type\x12$\n" +
	"\x02kv\x18\x02 \x01(\v2\x14.etcdcompat.KeyValueR\x02kv\x12-\n" +
	"\aprev_kv\x18\x03 \x01(\v2\x14.etcdcompat.KeyValueR\x06prevKv\" \n" +
	"\tEventType\x12\a\n" +
	"\x03PUT\x10\x00\x12\n" +
	"\n" +
	"\x06DELETE\x10\x01\"\x80\x05\n" +
	"\fRangeRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1b\n" +
	"\trange_end\x18\x02 \x01(\fR\brangeEnd\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x03R\brevision\x12A\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x0e2\".etcdcompat.RangeRequest.SortOrderR\tsortOrder\x12D\n" +
	"\vsort_target\x18\x06 \x01(\x0e2#.etcdcompat.RangeRequest.SortTargetR\n" +
	"sortTarget\x12\"\n" +
	"\fserializable\x18\a \x01(\bR\fserializable\x12\x1b\n" +
	"\tkeys_only\x18\b \x01(\bR\bkeysOnly\x12\x1d\n" +
	"\n" +
	"count_only\x18\t \x01(\bR\tcountOnly\x12(\n" +
	"\x10min_mod_revision\x18\n" +
	" \x01(\x03R\x0eminModRevision\x12(\n" +
	"\x10max_mod_revision\x18\v \x01(\x03R\x0emaxModRevision\x12.\n" +
	"\x13min_create_revision\x18\f \x01(\x03R\x11minCreateRevision\x12.\n" +
	"\x13max_create_revision\x18\r \x01(\x03R\x11maxCreateRevision\".\n" +
	"\tSortOrder\x12\b\n" +
	"\x04NONE\x10\x00\x12\n" +
	"\n" +
	"\x06ASCEND\x10\x01\x12\v\n" +
	"\aDESCEND\x10\x02\"B\n" +
	"\n" +
	"SortTarget\x12\a\n" +
	"\x03KEY\x10\x00\x12\v\n" +
	"\aVERSION\x10\x01\x12\n" +
	"\n" +
	"\x06CREATE\x10\x02\x12\a\n" +
	"\x03MOD\x10\x03\x12\t\n" +
	"\x05VALUE\x10\x04\"\x95\x01\n" +
	"\rRangeResponse\x122\n" +
	"\x06header\x18\x01 \x01(\v2\x1a.etcdcompat.ResponseHeaderR\x06header\x12&\n" +
	"\x03kvs\x18\x02 \x03(\v2\x14.etcdcompat.KeyValueR\x03kvs\x12\x12\n" +
	"\x04more\x18\x03 \x01(\bR\x04more\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\"\xa9\x01\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x14\n" +
	"\x05lease\x18\x03 \x01(\x03R\x05lease\x12\x17\n" +
	"\aprev_kv\x18\x04 \x01(\bR\x06prevKv\x12!\n" +
	"\fignore_value\x18\x05 \x01(\bR\vignoreValue\x12!\n" +
	"\fignore_lease\x18\x06 \x01(\bR\vignoreLease\"p\n" +
	"\vPutResponse\x122\n" +
	"\x06header\x18\x01 \x01(\v2\x1a.etcdcompat.ResponseHeaderR\x06header\x12-\n" +
	"\aprev_kv\x18\x02 \x01(\v2\x14.etcdcompat.KeyValueR\x06prevKv\"\\\n" +
	"\x12DeleteRangeRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1b\n" +
	"\trange_end\x18\x02 \x01(\fR\brangeEnd\x12\x17\n" +
	"\aprev_kv\x18\x03 \x01(\bR\x06prevKv\"\x94\x01\n" +
	"\x13DeleteRangeResponse\x122\n" +
	"\x06header\x18\x01 \x01(\v2\x1a.etcdcompat.ResponseHeaderR\x06header\x12\x18\n" +
	"\adeleted\x18\x02 \x01(\x03R\adeleted\x12/\n" +
	"\bprev_kvs\x18\x03 \x03(\v2\x14.etcdcompat.KeyValueR\aprevKvs\"\xc2\x03\n" +
	"\aCompare\x129\n" +
	"\x06result\x18\x01 \x01(\x0e2!.etcdcompat.Compare.CompareResultR\x06result\x129\n" +
	"\x06target\x18\x02 \x01(\x0e2!.etcdcompat.Compare.CompareTargetR\x06target\x12\x10\n" +
	"\x03key\x18\x03 \x01(\fR\x03key\x12\x1a\n" +
	"\aversion\x18\x04 \x01(\x03H\x00R\aversion\x12)\n" +
	"\x0fcreate_revision\x18\x05 \x01(\x03H\x00R\x0ecreateRevision\x12#\n" +
	"\fmod_revision\x18\x06 \x01(\x03H\x00R\vmodRevision\x12\x16\n" +
	"\x05value\x18\a \x01(\fH\x00R\x05value\x12\x1b\n" +
	"\trange_end\x18@ \x01(\fR\brangeEnd\"@\n" +
	"\rCompareResult\x12\t\n" +
	"\x05EQUAL\x10\x00\x12\v\n" +
	"\aGREATER\x10\x01\x12\b\n" +
	"\x04LESS\x10\x02\x12\r\n" +
	"\tNOT_EQUAL\x10\x03\"<\n" +
	"\rCompareTarget\x12\v\n" +
	"\aVERSION\x10\x00\x12\n" +
	"\n" +
	"\x06CREATE\x10\x01\x12\a\n" +
	"\x03MOD\x10\x02\x12\t\n" +
	"\x05VALUE\x10\x03B\x0e\n" +
	"\ftarget_union\"\xa1\x02\n" +
	"\tRequestOp\x12?\n" +
	"\rrequest_range\x18\x01 \x01(\v2\x18.etcdcompat.RangeRequestH\x00R\frequestRange\x129\n" +
	"\vrequest_put\x18\x02 \x01(\v2\x16.etcdcompat.PutRequestH\x00R\n" +
	"requestPut\x12R\n" +
	"\x14request_delete_range\x18\x03 \x01(\v2\x1e.etcdcompat.DeleteRangeRequestH\x00R\x12requestDeleteRange\x129\n" +
	"\vrequest_txn\x18\x04 \x01(\v2\x16.etcdcompat.TxnRequestH\x00R\n" +
	"requestTxnB\t\n" +
	"\arequest\"\xaf\x02\n" +
	"\n" +
	"ResponseOp\x12B\n" +
	"\x0eresponse_range\x18\x01 \x01(\v2\x19.etcdcompat.RangeResponseH\x00R\rresponseRange\x12<\n" +
	"\fresponse_put\x18\x02 \x01(\v2\x17.etcdcompat.PutResponseH\x00R\vresponsePut\x12U\n" +
	"\x15response_delete_range\x18\x03 \x01(\v2\x1f.etcdcompat.DeleteRangeResponseH\x00R\x13responseDeleteRange\x12<\n" +
	"\fresponse_txn\x18\x04 \x01(\v2\x17.etcdcompat.TxnResponseH\x00R\vresponseTxnB\n" +
	"\n" +
	"\bresponse\"\x9d\x01\n" +
	"\n" +
	"TxnRequest\x12-\n" +
	"\acompare\x18\x01 \x03(\v2\x13.etcdcompat.CompareR\acompare\x12/\n" +
	"\asuccess\x18\x02 \x03(\v2\x15.etcdcompat.RequestOpR\asuccess\x12/\n" +
	"\afailure\x18\x03 \x03(\v2\x15.etcdcompat.RequestOpR\afailure\"\x95\x01\n" +
	"\vTxnResponse\x122\n" +
	"\x06header\x18\x01 \x01(\v2\x1a.etcdcompat.ResponseHeaderR\x06header\x12\x1c\n" +
	"\tsucceeded\x18\x02 \x01(\bR\tsucceeded\x124\n" +
	"\tresponses\x18\x03 \x03(\v2\x16.etcdcompat.ResponseOpR\tresponses\"\x80\x02\n" +
	"\fWatchRequest\x12G\n" +
	"\x0ecreate_request\x18\x01 \x01(\v2\x1e.etcdcompat.WatchCreateRequestH\x00R\rcreateRequest\x12G\n" +
	"\x0ecancel_request\x18\x02 \x01(\v2\x1e.etcdcompat.WatchCancelRequestH\x00R\rcancelRequest\x12M\n" +
	"\x10progress_request\x18\x03 \x01(\v2 .etcdcompat.WatchProgressRequestH\x00R\x0fprogressRequestB\x0f\n" +
	"\rrequest_union\"\x95\x02\n" +
	"\x12WatchCreateRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1b\n" +
	"\trange_end\x18\x02 \x01(\fR\brangeEnd\x12%\n" +
	"\x0estart_revision\x18\x03 \x01(\x03R\rstartRevision\x12'\n" +
	"\x0fprogress_notify\x18\x04 \x01(\bR\x0eprogressNotify\x120\n" +
	"\afilters\x18\x05 \x03(\x0e2\x16.etcdcompat.FilterTypeR\afilters\x12\x17\n" +
	"\aprev_kv\x18\x06 \x01(\bR\x06prevKv\x12\x19\n" +
	"\bwatch_id\x18\a \x01(\x03R\awatchId\x12\x1a\n" +
	"\bfragment\x18\b \x01(\bR\bfragment\"/\n" +
	"\x12WatchCancelRequest\x12\x19\n" +
	"\bwatch_id\x18\x01 \x01(\x03R\awatchId\"\x16\n" +
	"\x14WatchProgressRequest\"\xab\x02\n" +
	"\rWatchResponse\x122\n" +
	"\x06header\x18\x01 \x01(\v2\x1a.etcdcompat.ResponseHeaderR\x06header\x12\x19\n" +
	"\bwatch_id\x18\x02 \x01(\x03R\awatchId\x12\x18\n" +
	"\acreated\x18\x03 \x01(\bR\acreated\x12\x1a\n" +
	"\bcanceled\x18\x04 \x01(\bR\bcanceled\x12)\n" +
	"\x10compact_revision\x18\x05 \x01(\x03R\x0fcompactRevision\x12#\n" +
	"\rcancel_reason\x18\x06 \x01(\tR\fcancelReason\x12\x1a\n" +
	"\bfragment\x18\a \x01(\bR\bfragment\x12)\n" +
	"\x06events\x18\v \x03(\v2\x11.etcdcompat.EventR\x06events*%\n" +
	"\n" +
	"FilterType\x12\t\n" +
	"\x05NOPUT\x10\x00\x12\f\n" +
	"\bNODELETE\x10\x012\x82\x02\n" +
	"\x02KV\x12<\n" +
	"\x05Range\x12\x18.etcdcompat.RangeRequest\x1a\x19.etcdcompat.RangeResponse\x126\n" +
	"\x03Put\x12\x16.etcdcompat.PutRequest\x1a\x17.etcdcompat.PutResponse\x12N\n" +
	"\vDeleteRange\x12\x1e.etcdcompat.DeleteRangeRequest\x1a\x1f.etcdcompat.DeleteRangeResponse\x126\n" +
	"\x03Txn\x12\x16.etcdcompat.TxnRequest\x1a\x17.etcdcompat.TxnResponse2I\n" +
	"\x05Watch\x12@\n" +
	"\x05Watch\x12\x18.etcdcompat.WatchRequest\x1a\x19.etcdcompat.WatchResponse(\x010\x01B7Z5github.com/sanskarpan/raft-consensus/proto/etcdcompatb\x06proto3"

var (
	file_proto_etcdcompat_etcd_proto_rawDescOnce sync.Once
	file_proto_etcdcompat_etcd_proto_rawDescData []byte
)

func file_proto_etcdcompat_etcd_proto_rawDescGZIP() []byte {
	file_proto_etcdcompat_etcd_proto_rawDescOnce.Do(func() {
		file_proto_etcdcompat_etcd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_etcdcompat_etcd_proto_rawDesc), len(file_proto_etcdcompat_etcd_proto_rawDesc)))
	})
	return file_proto_etcdcompat_etcd_proto_rawDescData
}

var file_proto_etcdcompat_etcd_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_proto_etcdcompat_etcd_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_etcdcompat_etcd_proto_goTypes = []any{
	(FilterType)(0),              // 0: etcdcompat.FilterType
	(Event_EventType)(0),         // 1: etcdcompat.Event.EventType
	(RangeRequest_SortOrder)(0),  // 2: etcdcompat.RangeRequest.SortOrder
	(RangeRequest_SortTarget)(0), // 3: etcdcompat.RangeRequest.SortTarget
	(Compare_CompareResult)(0),   // 4: etcdcompat.Compare.CompareResult
	(Compare_CompareTarget)(0),   // 5: etcdcompat.Compare.CompareTarget
	(*ResponseHeader)(nil),       // 6: etcdcompat.ResponseHeader
	(*KeyValue)(nil),             // 7: etcdcompat.KeyValue
	(*Event)(nil),                // 8: etcdcompat.Event
	(*RangeRequest)(nil),         // 9: etcdcompat.RangeRequest
	(*RangeResponse)(nil),        // 10: etcdcompat.RangeResponse
	(*PutRequest)(nil),           // 11: etcdcompat.PutRequest
	(*PutResponse)(nil),          // 12: etcdcompat.PutResponse
	(*DeleteRangeRequest)(nil),   // 13: etcdcompat.DeleteRangeRequest
	(*DeleteRangeResponse)(nil),  // 14: etcdcompat.DeleteRangeResponse
	(*Compare)(nil),              // 15: etcdcompat.Compare
	(*RequestOp)(nil),            // 16: etcdcompat.RequestOp
	(*ResponseOp)(nil),           // 17: etcdcompat.ResponseOp
	(*TxnRequest)(nil),           // 18: etcdcompat.TxnRequest
	(*TxnResponse)(nil),          // 19: etcdcompat.TxnResponse
	(*WatchRequest)(nil),         // 20: etcdcompat.WatchRequest
	(*WatchCreateRequest)(nil),   // 21: etcdcompat.WatchCreateRequest
	(*WatchCancelRequest)(nil),   // 22: etcdcompat.WatchCancelRequest
	(*WatchProgressRequest)(nil), // 23: etcdcompat.WatchProgressRequest
	(*WatchResponse)(nil),        // 24: etcdcompat.WatchResponse
}
var file_proto_etcdcompat_etcd_proto_depIdxs = []int32{
	1,  // 0: etcdcompat.Event.type:type_name -> etcdcompat.Event.EventType
	7,  // 1: etcdcompat.Event.kv:type_name -> etcdcompat.KeyValue
	7,  // 2: etcdcompat.Event.prev_kv:type_name -> etcdcompat.KeyValue
	2,  // 3: etcdcompat.RangeRequest.sort_order:type_name -> etcdcompat.RangeRequest.SortOrder
	3,  // 4: etcdcompat.RangeRequest.sort_target:type_name -> etcdcompat.RangeRequest.SortTarget
	6,  // 5: etcdcompat.RangeResponse.header:type_name -> etcdcompat.ResponseHeader
	7,  // 6: etcdcompat.RangeResponse.kvs:type_name -> etcdcompat.KeyValue
	6,  // 7: etcdcompat.PutResponse.header:type_name -> etcdcompat.ResponseHeader
	7,  // 8: etcdcompat.PutResponse.prev_kv:type_name -> etcdcompat.KeyValue
	6,  // 9: etcdcompat.DeleteRangeResponse.header:type_name -> etcdcompat.ResponseHeader
	7,  // 10: etcdcompat.DeleteRangeResponse.prev_kvs:type_name -> etcdcompat.KeyValue
	4,  // 11: etcdcompat.Compare.result:type_name -> etcdcompat.Compare.CompareResult
	5,  // 12: etcdcompat.Compare.target:type_name -> etcdcompat.Compare.CompareTarget
	9,  // 13: etcdcompat.RequestOp.request_range:type_name -> etcdcompat.RangeRequest
	11, // 14: etcdcompat.RequestOp.request_put:type_name -> etcdcompat.PutRequest
	13, // 15: etcdcompat.RequestOp.request_delete_range:type_name -> etcdcompat.DeleteRangeRequest
	18, // 16: etcdcompat.RequestOp.request_txn:type_name -> etcdcompat.TxnRequest
	10, // 17: etcdcompat.ResponseOp.response_range:type_name -> etcdcompat.RangeResponse
	12, // 18: etcdcompat.ResponseOp.response_put:type_name -> etcdcompat.PutResponse
	14, // 19: etcdcompat.ResponseOp.response_delete_range:type_name -> etcdcompat.DeleteRangeResponse
	19, // 20: etcdcompat.ResponseOp.response_txn:type_name -> etcdcompat.TxnResponse
	15, // 21: etcdcompat.TxnRequest.compare:type_name -> etcdcompat.Compare
	16, // 22: etcdcompat.TxnRequest.success:type_name -> etcdcompat.RequestOp
	16, // 23: etcdcompat.TxnRequest.failure:type_name -> etcdcompat.RequestOp
	6,  // 24: etcdcompat.TxnResponse.header:type_name -> etcdcompat.ResponseHeader
	17, // 25: etcdcompat.TxnResponse.responses:type_name -> etcdcompat.ResponseOp
	21, // 26: etcdcompat.WatchRequest.create_request:type_name -> etcdcompat.WatchCreateRequest
	22, // 27: etcdcompat.WatchRequest.cancel_request:type_name -> etcdcompat.WatchCancelRequest
	23, // 28: etcdcompat.WatchRequest.progress_request:type_name -> etcdcompat.WatchProgressRequest
	0,  // 29: etcdcompat.WatchCreateRequest.filters:type_name -> etcdcompat.FilterType
	6,  // 30: etcdcompat.WatchResponse.header:type_name -> etcdcompat.ResponseHeader
	8,  // 31: etcdcompat.WatchResponse.events:type_name -> etcdcompat.Event
	9,  // 32: etcdcompat.KV.Range:input_type -> etcdcompat.RangeRequest
	11, // 33: etcdcompat.KV.Put:input_type -> etcdcompat.PutRequest
	13, // 34: etcdcompat.KV.DeleteRange:input_type -> etcdcompat.DeleteRangeRequest
	18, // 35: etcdcompat.KV.Txn:input_type -> etcdcompat.TxnRequest
	20, // 36: etcdcompat.Watch.Watch:input_type -> etcdcompat.WatchRequest
	10, // 37: etcdcompat.KV.Range:output_type -> etcdcompat.RangeResponse
	12, // 38: etcdcompat.KV.Put:output_type -> etcdcompat.PutResponse
	14, // 39: etcdcompat.KV.DeleteRange:output_type -> etcdcompat.DeleteRangeResponse
	19, // 40: etcdcompat.KV.Txn:output_type -> etcdcompat.TxnResponse
	24, // 41: etcdcompat.Watch.Watch:output_type -> etcdcompat.WatchResponse
	37, // [37:42] is the sub-list for method output_type
	32, // [32:37] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_proto_etcdcompat_etcd_proto_init() }
func file_proto_etcdcompat_etcd_proto_init() {
	if File_proto_etcdcompat_etcd_proto != nil {
		return
	}
	file_proto_etcdcompat_etcd_proto_msgTypes[9].OneofWrappers = []any{
		(*Compare_Version)(nil),
		(*Compare_CreateRevision)(nil),
		(*Compare_ModRevision)(nil),
		(*Compare_Value)(nil),
	}
	file_proto_etcdcompat_etcd_proto_msgTypes[10].OneofWrappers = []any{
		(*RequestOp_RequestRange)(nil),
		(*RequestOp_RequestPut)(nil),
		(*RequestOp_RequestDeleteRange)(nil),
		(*RequestOp_RequestTxn)(nil),
	}
	file_proto_etcdcompat_etcd_proto_msgTypes[11].OneofWrappers = []any{
		(*ResponseOp_ResponseRange)(nil),
		(*ResponseOp_ResponsePut)(nil),
		(*ResponseOp_ResponseDeleteRange)(nil),
		(*ResponseOp_ResponseTxn)(nil),
	}
	file_proto_etcdcompat_etcd_proto_msgTypes[14].OneofWrappers = []any{
		(*WatchRequest_CreateRequest)(nil),
		(*WatchRequest_CancelRequest)(nil),
		(*WatchRequest_ProgressRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_etcdcompat_etcd_proto_rawDesc), len(file_proto_etcdcompat_etcd_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_etcdcompat_etcd_proto_goTypes,
		DependencyIndexes: file_proto_etcdcompat_etcd_proto_depIdxs,
		EnumInfos:         file_proto_etcdcompat_etcd_proto_enumTypes,
		MessageInfos:      file_proto_etcdcompat_etcd_proto_msgTypes,
	}.Build()
	File_proto_etcdcompat_etcd_proto = out.File
	file_proto_etcdcompat_etcd_proto_goTypes = nil
	file_proto_etcdcompat_etcd_proto_depIdxs = nil
}
